name: Terraform
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
on: 
  # push:
  workflow_dispatch: 

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform fmt
              run: terraform fmt
            - name: Terraform Init
              run: terraform init

            - name: Terraform plan
              run: terraform plan

            - name: Terraform apply
              run: terraform apply -auto-approve